<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Revy Weather'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php //echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
              //          ->prependStylesheet($this->basePath() . '/css/style.css')
              //          ->prependStylesheet($this->basePath() . '/css/bootstrap-blue-sky.min.css') ?>

        <?php echo $this->muneeCss(array('/css/bootstrap-blue-sky.min.css', '/css/style.css'), true); ?>

        <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">

        <!-- Scripts -->
        <?php echo $this->muneeJs(array(
            '/js/jquery-2.0.3.min.js',
            '/js/bootstrap.min.js',
            '/js/raphael.2.1.0.min.js',
            '/js/justgage.1.0.1.min.js',
            '/js/jquery.scrollto.js',
            '/js/jquery.nav.js',
            '/js/nav.js',
            '/js/jquery.scrollToTop.min.js'
        ), true); ?>
        <script src="http://openlayers.org/api/OpenLayers.js"></script>
        <script src="http://maps.google.com/maps/api/js?v=3&amp;sensor=false"></script>
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',)) ?>
        <?php /**
            ->prependFile($this->basePath() . '/js/jquery.scrollToTop.min.js')
            ->prependFile($this->basePath() . '/js/nav.js')
            ->prependFile($this->basePath() . '/js/jquery.nav.js')
            ->prependFile($this->basePath() . '/js/jquery.scrollto.js')
            ->prependFile($this->basePath() . '/js/justgage.1.0.1.min.js')
            ->prependFile($this->basePath() . '/js/raphael.2.1.0.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery-2.0.3.min.js')
        */ ?>

    </head>
    <body>
        <a href="#top" id="toTop"><i class="icon-arrow-up"></i>&nbsp;&nbsp;Back to Top</a>
        <div class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Revy Weather') ?></a>
                </div>

                <div class="collapse navbar-collapse navbar-ex1-collapse">
                    <ul id="nav" class="nav navbar-nav">
                        <li class="active"><a href="#right-now">Right Now</a></li>
                        <li><a href="#live-webcam">Live Webcam</a></li>
                        <li><a href="#forecast">Forecast</a></li>
                        <li><a href="#map">Map</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="wrapper">
            <?php echo $this->content; ?>

            <div class="container">
                <hr>
                <footer>
                    <p class="text-muted">&copy; <?php echo date('Y') ?> Monashee Mountain Multimedia. <?php echo $this->translate('All rights reserved.') ?></p>
                </footer>
            </div>

        </div> <!-- .wrapper -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
