<div class="row">
    <div class="col-12">
        <h2>RIGHT NOW</h2>
        <div id="timestamp" class="timestamp"></div>
    </div>
</div>

<div class="row">

    <div class="col-6 col-sm-4 col-lg-4">
        <div id="temp" class="temp"></div>
        <div id="pressure" class="pressure"></div>
        <div id="humidity" class="humidity"></div>
        <div id="wind" class="wind"></div>
    </div>

    <div class="col-6 col-sm-4 col-lg-4">
        <div id="gauge-speed" style="width:200px; height:160px;"></div>
    </div>

    <div class="col-6 col-sm-4 col-lg-4">
        <div id="compass">
            <div id="arrow"></div>
        </div>​
    </div>
</div>
