<?php
/**
 * Home page for Revy Weather
 *
 * @author      Derek Marcinyshyn <derek@marcinyshyn.com>
 * @date        August 1, 2013
 */
?>

<?php $this->headScript()->offsetSetFile(100, '/js/weather.js'); ?>

<section id="right-now" class="right-now">
    <div class="container">
        <div class="col-lg-12 right-now-time">
            <h2>RIGHT NOW</h2>
            <h4>Courthouse Area</h4>
            <!-- <p class="text-very-muted"><small>Refreshed every 10 seconds</small></p> -->
            <div id="timestamp" class="timestamp text-muted"></div>
        </div>

        <div class="col-md-3">
            <div class="current-icon">
                <img alt="<?php echo $this->getWeather('Revelstoke')->getCondition(); ?>" src="/img/wx/icons-large/<?php echo $this->getWeather('Revelstoke')->getIconCode(); ?>.png" height="120" width="120" />
            </div>
            <div id="temp" class="temp"></div>
        </div>
        <div class="col-md-3">
            <div class="conditions-spacer">&nbsp;</div>
            <div id="condition" class="condition">Condition: <strong><?php echo $this->getWeather('Revelstoke')->getCondition(); ?></strong></div>
            <div id="pressure" class="pressure"></div>
            <div id="humidity" class="humidity"></div>
            <div id="wind" class="wind"></div>
        </div>
        <div class="col-md-3 right-now-spacer">
            <div id="gauge-speed" class="gauge-speed"></div>
        </div>
        <div class="col-md-3 right-now-spacer">
            <div id="compass">
                <div id="arrow"></div>
            </div>​
        </div>

        <div class="clearfix"></div>

        <div class="col-lg-12 right-now-time margin-top-40">
            <h4>Revelstoke Airport</h4>
            <div class="timestamp text-muted"><?php echo $this->getWeather('Revelstoke')->getDateTime(); ?></div>
        </div>
        <div class="col-md-3">
            <div class="current-icon">
                <img alt="<?php echo $this->getWeather('Revelstoke')->getCondition(); ?>" src="/img/wx/icons-large/<?php echo $this->getWeather('Revelstoke')->getIconCode(); ?>.png" height="120" width="120" />
            </div>
            <div id="temperature" class="temp"><?php echo $this->getWeather('Revelstoke')->getTemperature(); ?> &deg;C</div>
        </div>
        <div class="col-md-3">
            <div id="condition" class="condition">Condition: <strong><?php echo $this->getWeather('Revelstoke')->getCondition(); ?></strong></div>
            <div id="pressure" class="pressure">Pressure: <strong><?php echo $this->getWeather('Revelstoke')->getPressure(); ?> kPa</strong></div>
            <div id="humidity" class="humidity">Humidity: <strong><?php echo $this->getWeather('Revelstoke')->getRelativeHumidity(); ?>%</strong></div>
            <div id="wind" class="wind">Wind: <strong><?php echo $this->getWeather('Revelstoke')->getDirection(); echo '&nbsp;'; echo $this->getWeather('Revelstoke')->getSpeed(); ?>  km/h</strong></div>
        </div>
        <div class="col-md-3">
            <div id="visibility" class="visibility">Visibility: <strong><?php echo $this->getWeather('Revelstoke')->getVisibility(); ?> km</strong></div>
            <div id="dewpoint" class="dewpoint">Dewpoint: <strong><?php echo $this->getWeather('Revelstoke')->getDewpoint(); ?> &deg;C</strong></div>
            <div class="sunrise">Sunrise: <strong><?php echo $this->getWeather('Revelstoke')->getSunrise(); ?></strong></div>
            <div class="sunset">Sunset: <strong><?php echo $this->getWeather('Revelstoke')->getSunset(); ?></strong></div>
        </div>
        <div class="col-md-3">
            <div class="yesterday">Yesterday High Temperature: <strong><?php echo $this->getWeather('Revelstoke')->getHighTemp(); ?> &deg;C</strong></div>
            <div class="yesterday">Yesterday Low Temperature: <strong><?php echo $this->getWeather('Revelstoke')->getLowTemp(); ?> &deg;C</strong></div>
            <div class="yesterday">Yesterday Precipitation: <strong><?php echo $this->getWeather('Revelstoke')->getPrecip(); ?> mm</strong></div>
            <div class="yesterday">Record High Temp: <strong><?php echo $this->getWeather('Revelstoke')->getExtremeHigh(); ?></strong></div>
            <div class="yesterday">Record Low Temp: <strong><?php echo $this->getWeather('Revelstoke')->getExtremeLow(); ?></strong></div>
        </div>

        <div class="filler"></div>
    </div>
</section>


<section id="history" class="history">
    <div class="container">
        <div class="col-lg-12">
            <h2>HISTORICAL WEATHER</h2>
        </div>
        <div class="clearfix"></div>
        <div class="col-md-3">
            <div class="input-group">
                <input id="daterange" class="form-control" placeholder="Select date range" type="text"/>
                <span class="input-group-addon">
                    <i class="icon-calendar"></i>
                </span>
            </div>
        </div>

        <div class="clearfix"></div>

        <div id="high-charts-container" class="col-lg-12 high-charts-container"></div>

        <div class="filler"></div>
        <div class="filler"></div>
        <div class="filler"></div>
        <div class="filler"></div>
    </div>
</section>


<section id="live-webcam" class="live-webcam">
    <div class="container">
        <div class="col-lg-12">
            <h2>LIVE WEBCAM</h2>
            <p><small>Refreshed every 5 minutes</small></p>
        </div>
        <div class="col-lg-12">
            <img src="/img/latest.jpg?<?php echo time() ?>" width="1280" height="720" alt="live-webcam" id="webcam-latest" class="img-rounded img-responsive webcam"/>
        </div>

        <div class="filler"></div>
    </div>
</section>

<section id="forecast" class="forecast">
    <div class="container">
        <div class="col-lg-12">
            <h2>FORECAST</h2>
            <div class="forecast-container">
                <?php // loop through the forecast period ?>
                <?php for ($count = 0; $count <= 6; $count++) : ?>
                    <div class="forecast-period">
                        <h3><?php echo $this->getWeather('Revelstoke')->getForecastPeriod($count); ?></h3>
                        <p><img alt="<?php echo $this->getWeather('Revelstoke')->getAbbreviatedTextSummary($count); ?>" src="/img/wx/icons-large/<?php echo $this->getWeather('Revelstoke')->getForecastIconCode($count); ?>.png" height="64" width="64" />
                        &nbsp;&nbsp;<?php echo $this->getWeather('Revelstoke')->getForecastTextSummary($count); ?></p>
                    </div>
                <?php endfor; ?>
            </div>
        </div>

        <div class="filler"></div>
    </div>
</section>

<section id="map" class="map">
    <div class="container">
        <div class="col-lg-12">
            <h2>WEATHER MAP</h2>
            <div id="map-container" class="map-container"></div>
        </div>

        <div class="filler"></div>
    </div>
</section>

<section id="timelapse" class="timelapse">
    <div class="container">
        <h2>TIMELAPSE VIDEOS</h2>
        <div class="timelapse-container">
            <div class="list-group">
                <?php $iterator = $this->bucketList('monashee-mountain-multimedia-timelapse'); ?>
                <?php $count = 0; ?>
                <?php foreach ($iterator as $object) : ?>
                    <?php $split = explode("/", $object['Key']); ?>
                    <?php $year = $split[0]; $month = $split[1];  $day = $split[2]; ?>
                    <?php $video = $year . "/" . $month . "/" . $day . "/" . $month . "-" . $day; ?>
                    <?php if ($count %2 == 0) : ?>
                        <a class="list-group-item" data-toggle="modal" role="dialog" href="#video-modal-<?php echo $day ?>"><?php echo $month . ' ' . $day . ', ' . $year; ?></a>
                        <div id="video-modal-<?php echo $day ?>" class="modal fade" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                        <h4 class="modal-title"><?php echo $month . ' ' . $day . ', ' . $year; ?></h4>
                                    </div>
                                    <div class="modal-body">
                                        <div class="video-wrapper">
                                            <video controls autoplay="none">
                                                <source src="http://video.revyweather.com/<?php echo $video ?>.webm" type="video/webm">
                                                <source src="http://video.revyweather.com/<?php echo $video ?>.mp4" type="video/mp4">
                                                Your browser does not support modern technologies.
                                            </video>
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        &nbsp;
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endif; ?>
                    <?php $count++; ?>
                <?php endforeach; ?>
            </div>
        </div>

        <div class="filler"></div>
        <div class="filler"></div>
        <div class="filler"></div>
    </div>
</section>